spring:
  main:
    web-application-type: none
  flyway:
    locations: classpath:/db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jackson:
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss
app:
  constants:
    bot:
      bot-name: Anonymous Kitten Comments
      bot-token: ${BOT_TOKEN}
      channel-id: ${CHANNEL_ID}
      chat-group-id: ${CHAT_GROUP_ID}
      comments-list-chat-id: ${COMMENTS_LIST_CHAT_ID}
      link-to-message: ${LINK_TO_MESSAGE}
      bot-link: ${BOT_LINK}
      language: ${BOT_LANGUAGE}
